-- task_4.sql
-- PRINT THE FULL DESCRIPTION OF THE 'BOOKS' TABLE IN ALX_BOOK_STORE
-- WITHOUT USING DESCRIBE, EXPLAIN, OR ANALYZE

USE alx_book_store;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'alx_book_store'
  AND TABLE_NAME = 'Books';
